baseURL = "https://corpusabierto.com/"
languageCode = "es-ES"
title = "CorpusAbierto"
publishDir = "docs"
disableKinds = ["taxonomy"]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Esto es lo que soluciona el problema.
      # Le dice a Hugo que confíe en el HTML generado por Goldmark.
      unsafe = true